name=input("请输入姓名：")
sex=input("请输入性别:")
age=int(input("请输入年龄:"))
phone=input("请输入手机号:")
nation=input("请输入民族:")
QQ=input("请输入QQ号码:")
add=input("请输入家庭住址:")
height=float(input("请输入身高:"))
weight=float(input("请输入体重:"))

print("我的名字叫 %s"%name)
print("我的性别是 %s"%sex)
print("我的年龄是 %d"%age)
print("我的手机号是 %s"%phone)
print("我的名族是 %s"%nation)
print("我的QQ是 %s"%QQ)
print("我的家庭住址是 %s"%add)
print("我的身高是 %.02f"%height)
print("我的体重是 %.02f"%weight)

